# Usa a imagem base do Airflow
FROM apache/airflow:3.1.0

# Instala as dependências do Data Pipeline
USER root

# Instala as dependências do sistema necessárias
RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

RUN curl -Lo /usr/bin/mc https://dl.min.io/client/mc/release/linux-amd64/mc && \
    chmod +x /usr/bin/mc

# Instala as bibliotecas Python necessárias
USER airflow
RUN pip install --no-cache-dir \
    "polars[parquet]" \
    "requests" \
    "minio" \
    "boto3" \
    "pandas" \
    "pytest" \
    "pandera" \
    "awscli"
